version: '1.0'
services:
  app:
    container_name: "thanks-friend"
    restart: always
    build: .
    environment:
      - DATABASE_URL = ${DATABASE_URL}
      - APP_PORT = ${APP_PORT}
      - JWT_SECRET = ${JWT_SECRET}
    ports:
      - 8080:8080
    command: npm start

  